//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Site {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Site() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Site", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7-8 avril 2018.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13e édition.
        /// </summary>
        internal static string Edition {
            get {
                return ResourceManager.GetString("Edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Éditions précédentes.
        /// </summary>
        internal static string Editions {
            get {
                return ResourceManager.GetString("Editions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le LAN Party.
        /// </summary>
        internal static string LAN {
            get {
                return ResourceManager.GetString("LAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24 heures de jeu intensif.
        /// </summary>
        internal static string LAN2 {
            get {
                return ResourceManager.GetString("LAN2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gymnase du Cégep de Sept-Îles.
        /// </summary>
        internal static string Lieu {
            get {
                return ResourceManager.GetString("Lieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le SLAN Revolution, c&apos;est une nuit complète où des joueurs de jeux vidéos peuvent jouer ensemble en réseau local ou en ligne au Cégep de Sept-Iles. Organisé entièrement bénévolement par les étudiants en Techniques de l&apos;informatique, l&apos;évènement se déroule dans le gymnase du collège, regroupant maintenant plus de 200 participants..
        /// </summary>
        internal static string Presentation {
            get {
                return ResourceManager.GetString("Presentation", resourceCulture);
            }
        }
    }
}
